insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Orbital ATK', 'orbital_avatar.png', 'S Freeport Industrial Pkwy', 'Clearfield', 'UT', '84015', 'careers@OrbitalATK.com', 'https://www.orbitalatk.com/about/company-overview/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Petersen Inc', 'peterson_avatar.jpg', '1527 N 2000 W', 'Ogden', 'UT', '84404', 'HR@peterseninc.com', 'https://www.peterseninc.com/mission-vision/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Lifetime Products', 'lifetime_avatar.png', 'Building D12, S Freeport Industrial Pkwy', 'Clearfield', 'UT', '84016', 'CustomerCare@lifetime.com ', 'https://www.lifetime.com/company/employment');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Barnes Group', 'barnes_avatar.jpg', '1025 Depot Dr', 'Ogden', 'UT', '84404', 'bgicareers@bginc.com', 'http://www.barnesgroupinc.com/about-bgi/company-values.aspx');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4121, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3021, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('IM Flash', 'im_avatar.jpg', '4000 N Flash Dr', 'Lehi', 'UT', '84043', '', 'http://www.imflash.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3024, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Merit Medical', 'merit_avatar.png', '1600 Merit Pkwy', 'South Jordan', 'UT', '84095', 'recruiting@merit.com', 'https://www.merit.com/careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('BD', 'bg_avatar.png', '9450 State St', 'Sandy', 'UT', '84070', '', 'http://www.bd.com/en-us/company');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3024, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9021, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9071, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Edwards Lifesciences', 'edwards_avatar.png', '12050 Lone Peak Pkwy', 'Draper', 'UT', '84020', '', 'http://www.edwards.com/aboutus/OurHistory');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Nestle', 'nestle_avatar.png', '815 Raymond Klauck Way', 'Springville', 'UT', '84663', '', 'http://www.nestleusa.com/about-us');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3027, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('1-800-Contacts', 'contacts_avatar.png', '261 Data Dr', 'Draper', 'UT', '84020', '', 'https://www.1800contacts.com/the-company.html');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1134, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1141, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1151, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Cummins', 'cummins_avatar.jpg', '2167 S 5370 W', 'West Valley City', 'UT', '84120', '', 'http://careers.cummins.com/us-canada/working-right/career-development');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3027, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 3031, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Autoliv', 'autoliv_avatar.png', '3350 Airport Rd', 'Ogden', 'UT', '84405', '', 'https://www.autoliv.com//AboutUs/Pages/InBrief/default.aspx');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1142, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1143, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1152, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1134, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('IHC', 'ihc_avatar.png', '36 S State St, Fl 22', 'Salt Lake City', 'UT', '84111', 'recruitment@imail.org', 'https://intermountainhealthcare.org/careers/explore-careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 1141, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2034, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2052, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2057, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2055, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 1126, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2061, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2071, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1134, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('ARUP', 'arup_avatar.png', '500 Chipeta Way', 'Salt Lake City', 'UT', '84108', 'hr@aruplab.com', 'http://www.aruplab.com/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1134, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('U of U Hospital', 'uofu_avatar.png', '50 N Medical Dr', 'Salt Lake City', 'UT', '84112', '', 'https://healthcare.utah.edu/about/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(47, 2031, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(47, 2111, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1151, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 1141, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2052, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2053, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2031, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2061, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Revere Health', 'revere_avatar.png', '1055 N 500 W', 'Provo', 'UT', '84604', '', 'http://reverehealth.com/about/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2035, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2032, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2071, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2057, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2034, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('HCA Mountainstar', 'mountain_star.png', '6985 S Union Park Center #500', 'Cottonwood Heights', 'UT', '84047', '', 'http://mountainstar.com/careers/search.dot');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 1141, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2032, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2034, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2035, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2052, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2053, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2055, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2061, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2071, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 1141, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Rio Tinto', 'riotinto_avatar.png', '4700 Daybreak Parkway', 'South Jordan', 'UT', '84095', '', 'http://www.riotinto.com/careers/why-join-rio-tinto-3178.aspx');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('WW Clyde', 'wwclyde.png', '869 N 1500 W', 'Orem', 'UT', '84057', '', 'https://wwclyde.net/our-story/company/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Hunt Electric', 'hunt_avatar.jpg', '1863 W Alexander Street', 'Salt Lake City', 'UT', '84119', '', 'https://www.huntelectric.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(47, 2111, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1142, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Cache Valley Electric', 'cache_avatar.png', '1414 Gustin Rd W', 'Salt Lake City', 'UT', '84104', '', 'http://www.cve.com/about-cve/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Wheeler Machinery', 'wheeler_avatar.jpg', '4901 2100 S', 'Salt Lake City', 'UT', '84120', '', 'http://careers.wheelercat.com/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 3041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Dominion Energy', 'dominion_avatar.jpg', '333 S State St', 'Salt Lake City', 'UT', '84111', '', 'https://www.dominionenergy.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Vivint Solar', 'vivint_avatar.jpg', '1800 Ashton Blvd', 'Lehi', 'UT', '84043', 'help@vivintsolar.com', 'https://www.vivintsolar.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(47, 2111, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Auric Solar', 'auric_avatar.png', '2310 S 1300 W', 'West Valley City', 'UT', '84119', '', 'https://www.auricsolar.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(47, 2111, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Sorenson Communications', 'sorenson_avatar.jpg', '192 s Riverboat Rd', 'Salt Lake City', 'UT', '84123', '', 'http://www.sorenson.com/jobs');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1134, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1141, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1142, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1143, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1151, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1152, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Alorica', 'alorica_avatar.png', ' 8285 W 3500 S', 'Magna', 'UT', '84044', '', 'https://www.alorica.com/careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(15, 1151, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Hexcel', 'hexcel_avatar.png', '6700 W 5400 S', 'West Valley City', 'UT', '84118', '', 'http://hexcel.com/Careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3021, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(47, 2111, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9044, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Albany', 'albany_avatar.png', '5995 W Amelia Earhart Dr', 'Salt Lake City', 'UT', '84116', '', 'http://www.albint.com/en-us/company/Pages/Careers.aspx');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3021, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Nammo - Composite', 'namno_avatar.jpg', '1000 S 500 W', 'Salt Lake City', 'UT', '84101', '', 'http://www.nammo-cs.com/our-company/what-we-do');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3021, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Boeing', 'boeing_avatar.jpg', '1215 2200 W', 'Salt Lake City', 'UT', '84116', '', 'http://www.boeing.com/careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9041, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9071, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('L-3', 'l3_avatar.JPG', '640 2200 W', 'Salt Lake City', 'UT', '84116', '', 'http://www2.l3t.com/csw/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 4012, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('ENVE', 'enve_avatar.png', '508 W. Stockman Way', 'Ogden', 'UT', '84401', '', 'https://enve.com/company/careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3027, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Campbell Scientific', 'campbell_avatar.jpg', '815 W 1800 N ', 'Logan', 'UT', '84321', '', 'https://www.campbellsci.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Andeavor(Tesoro)', 'andeavor.jpg', '474 W 900 N', 'Salt Lake City', 'UT', '84103', '', 'http://www.andeavor.com/careers/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('BioFire', 'biofire_avatar.jpg', '515 Colorow Dr', 'Salt Lake City', 'UT', '84108', '', 'http://www.biofiredx.com/company/career/');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9021, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3029, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 9071, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(29, 2011, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3027, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Burt Brothers', 'burtbrothers_avatar.png', '944 E 2100 S', 'Salt Lake City', 'UT', '84106', '', 'https://burtbrothers.com/company');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Jiffy Lube', 'jiffylube_avatar.jpg', '757 W North Temple', 'Salt Lake City', 'UT', '84116', '', 'https://www.jiffylube.com/careers');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(49, 3023, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employers(title, image_avatar_url, address, city, state, zipcode, email, overview_link) values('Parker Hannifin', 'parker_avatar.jpg', '2220 3600 W', 'West Valley City', 'UT', '84119', '', 'http://www.parker.com/portal/site/PARKER/menuitem.e631b67dc0285c0566b049e1237ad1ca/?vgnextoid=243880961f66e010VgnVCM1000000308a8c0RCRD&vgnextfmt=default');
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(51, 2092, (SELECT currval('gilded_public.employers_id_seq')));
insert into gilded_public.employeroccupations(field_id, soc_id, employer_id)values(17, 3021, (SELECT currval('gilded_public.employers_id_seq')));
