insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'CNC Machining', 4655, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Automation Technology', 3949, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Plastic Injection Molding Technology', 3212, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Welding', 6000, 13, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Software Development', 3268, 13, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Manual Machinist', 1407, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding', 3468, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Machinist Level I', 3595, 8, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Machinist Level II', 4240, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Machinist Level III', 5073, 14, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Computer Aided Design', 3949, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Welder Metal Fabricator', 2535, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (4,'Precision Machining', 5236, 10.5, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (4,'Web Programming&Development', 3800, 13, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Welding Technician II', 2776, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Medical Billing and Coding', 1793, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2071, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Industrial Maintenance Technician', 2624, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Machining Technology - Conventional', 3420, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Machining Technology - CNC', 5130, 15, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Web and Mobile Development', 2480, 10, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Machine Tool Technology', 6965, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Advanced Networking', 8884, 24, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1143, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Networking', 4442, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Server Administration', 4442, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Advanced Server Administration', 4442, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Production Operations & Controls Emphasis', 11046, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Production Operations & Controls Emphasis', 22092, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Welding Emphasis', 11046, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Welding Emphasis', 22092, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Mechanical Engineering Technology', 11046, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3026, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3027, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Mechanical Engineering Technology', 22092, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3026, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3027, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Electronics Engineering Technology', 11046, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Electronics Engineering Technology', 22092, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Controls Technology', 11046, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3026, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Associate of Applied Science in Computer Science', 11046, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automotive Technician', 13400, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automotive Collision Repair and Refinishing', 12881, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automotive Collision Repair and Refinishing', 5928, 8, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding Fabrication', 12225, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding Technology', 6800, 8, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding (KWLD)', 3900, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Clinical Lab Assistant', 1550, 3, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Air Conditioning / Heating / Refrigeration (KACC)', 3592, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Diesel Systems Technolog', 19526, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electromechanical Assembly Technician (KEM2)', 1947, 3, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automation & Instrumentation Technician (KAIT)', 4577, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9071, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electronics Communications Technician (KEC3)', 3985, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electronics Engineering Technician (KEET)', 3237, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electronics Technician (KET2)', 2977, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Manual Machinist (KMAT)', 1429, 3, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Medical Coding & Billing (KMC2)', 3557, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2071, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Network Systems: AAS (CTE)', 11061, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Web Development', 4541, 12, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (10,'Database Certificate', 8190, 12, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1141, (SELECT currval('gilded_public.programs_id_seq')));
