insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'CNC Machining', 4655, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Automation Technology', 3949, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Plastic Injection Molding Technology', 3212, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Welding', 6000, 13, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Software Development', 3268, 13, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Manual Machinist', 1407, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding', 3468, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Machinist Level I', 3595, 8, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Machinist Level II', 4240, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Machinist Level III', 5073, 14, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Computer Aided Design', 3949, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Welder Metal Fabricator', 2535, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (4,'Precision Machining', 5236, 10.5, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (4,'Web Programming&Development', 3800, 13, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Welding Technician II', 2776, 11, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Medical Billing and Coding', 1793, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2071, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Industrial Maintenance Technician', 2624, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Machining Technology - Conventional', 3420, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Machining Technology - CNC', 5130, 15, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Web and Mobile Development', 2480, 10, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Machine Tool Technology', 6965, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Advanced Networking', 8884, 24, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1143, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Networking', 4442, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Server Administration', 4442, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Computer Information Technology - Advanced Server Administration', 4442, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Production Operations & Controls Emphasis', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Production Operations & Controls Emphasis', 25248, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Welding Emphasis', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Manufacturing Engineering Technology: Welding Emphasis', 25248, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Mechanical Engineering Technology', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3026, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3027, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Mechanical Engineering Technology', 25248, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3026, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3027, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3029, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Electronics Engineering Technology', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Electronics Engineering Technology', 25248, 44, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Controls Technology', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3026, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Associate of Applied Science in Computer Science', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automotive Technician', 13400, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automotive Collision Repair and Refinishing', 12881, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automotive Collision Repair and Refinishing', 5928, 8, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding Fabrication', 12225, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding Technology', 6800, 8, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Welding (KWLD)', 3900, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4121, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Clinical Lab Assistant', 1550, 3, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Air Conditioning / Heating / Refrigeration (KACC)', 3592, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Diesel Systems Technolog', 19526, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electromechanical Assembly Technician (KEM2)', 1947, 3, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Automation & Instrumentation Technician (KAIT)', 4577, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3024, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9071, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electronics Communications Technician (KEC3)', 3985, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electronics Engineering Technician (KEET)', 3237, 7, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Electronics Technician (KET2)', 2977, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3023, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Manual Machinist (KMAT)', 1429, 3, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 4041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Medical Coding & Billing (KMC2)', 3557, 6, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2071, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Network Systems: AAS (CTE)', 11061, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1143, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Web Development', 4541, 12, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (10,'Database Certificate', 8190, 12, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1141, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Engineering Design / Drafting Technology (AAS)', 12225, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Design Engineering Technology (AAS)', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Civil/Environmental Engineering: APE(CTE)', 19526, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3025, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Civil and Environmental Engineering (APE)', 8844, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3025, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Radiologic Technology (AAS)', 12624, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2034, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Network Engineer: CP (Competency-Based)(CTE)', 12225, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1142, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1151, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Respiratory Therapy: AAS (CTE)', 15625, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 1126, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Aerospace/Aviation Technology Maintence (AAS)', 16302, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (11,'Aircraft Maintenance Technician- Airframe & Powerplant - AAS', 12624, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Radiologic Technology: AAS (CTE)', 13875, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 1124, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2034, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,' Radiologic Technology: AAS ', 21478, 36, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 1124, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Respiratory Therapy, Pre-Professional (AAS)', 15913, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 1126, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Registered Nurse (AAS)', 12765, 28, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 1141, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Registered Nurse (ADN)', 19130, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 1141, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Medical Laboratory Sciences (AAS)', 14275, 20, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (8,'Clinical Lab Assistant', 2776, 5, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2012, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Dential Hygiene ', 23000, 28, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Dential Hygiene ', 21000, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'EMT', 1937, 3, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'EMT', 766, 7, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Pharmacy Technician', 2170, 8, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2052, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Pharmacy Technician', 2729, 9, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2052, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Respiratory Therapy: AAS (CTE)', 17265, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2054, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Respiratory Therapy: AAS Pre-Professional', 15940, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2054, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Surgical Technology (CC)', 7220, 16, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2055, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Surgical Technology', 4745, 18, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2055, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Veterinarian Assistant/Pre-Vet Tech', 1380, 10, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2056, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (12,'Veterinary Assistant ', 15800, 12, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2056, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (7,'Engineering Technology: CAD/CAM Technology (AAS)', 16551, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(17, 3011, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Nutrition', 10184, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2051, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Industrial Mechanics AAS', 10184, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9044, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Industrial Mechanics Certificate of Completion', 5092, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 9044, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (11,'Agricultural Machinery Technology AAS, Cert', 16064, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (11,'Agricultural Machinery Technology Cert only', 8032, 12, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3041, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (11,'Diesel and Heavy Equipment Mechanics - AAS', 16064, 23, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(49, 3031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Dental Hygiene AAS (CTE)', 24990, 36, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Dental Hygiene AS', 20736, 36, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2021, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'Apprenticeship Electrical Independent Technology: AAS (CTE)', 14760, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2111, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Electrician Apprentice', 3531, 48, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2111, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Nuclear Medicine', 27648, 48, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2033, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'COMPUTER SCIENCES AND INFORMATION SYSTEMS: AS', 12765, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'COMPUTER SCIENCES AND INFORMATION SYSTEMS: AAS (CTE)', 13000, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(15, 1134, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (6,'Diagnostic Medical Sonography', 28000, 48, FALSE, 'Bachelor''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2032, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (5,'Apprenticeship Plumber', 3000, 48, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Plumbing Apprentice', 3000, 48, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Practical Nursing', 4015, 9, TRUE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2061, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (9,'Practical Nursing', 11076, 18, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(29, 2061, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (3,'Construction Technology', 745, 2, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2022, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'APPRENTICESHIP CARPENTRY JATC TECHNOLOGY: AAS (CTE)', 13000, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'APPRENTICESHIP CARPENTRY INDEPENDENT TECHNOLOGY: AAS (CTE)', 14000, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2031, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'APPRENTICESHIP PLUMBER/PIPEFITTER JATC TECHNOLOGY: AAS (CTE)', 14000, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (1,'APPRENTICESHIP PLUMBER INDEPENDENT TECHNOLOGY: AAS (CTE)', 13000, 24, FALSE, 'Associate''s');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(47, 2152, (SELECT currval('gilded_public.programs_id_seq')));
insert into gilded_public.programs(school_id, title, cost_in_state, length_months, flexible_schedule, credential) values (2,'Utah Aerospace Pathways', 450, 5, FALSE, 'Certificate');
insert into gilded_public.occupationprograms(field_id, soc_id, program_id) values(51, 2092, (SELECT currval('gilded_public.programs_id_seq')));

